config/routes.rb
Rails.application.routes.draw do
  resources :articles
  devise_for :users, path: 'user',
             path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret',
                           confirmation: 'verification', unlock: 'unblock', registration: 'register',
                           sign_up: 'sign_up' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get '/p/:slug', to: 'articles#show_by_slug', as: 'post'
  # Defines the root path route ("/")
  root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, :brief, :content_md, presence: true
  validates :slug, uniqueness: { case_sensitive: false }
  enum :category, [ :general, :misc, :trips, :repairs ]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, except: %i[ index show_by_slug ]
  before_action :set_article_by_slug, only: %i[ show_by_slug ]
  before_action :set_article, only: %i[ show edit update destroy ]

  # GET /articles or /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1 or /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles or /articles.json
  def create
    @article = Article.new(article_params)
    markdown = init_markdown
    @article[:content_html] = markdown.render(@article[:content_md])
    @article[:slug] = generate_slug(@article)
    respond_to do |format|
      if @article.save
        format.html { redirect_to article_url(@article), notice: "Article was successfully created." }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    respond_to do |format|
      # @article[:content_html] = markdown.render(@article[:content_md])
      if @article.update(article_params)
        markdown = init_markdown
        @article.update(content_html: markdown.render(@article[:content_md]))
        format.html { redirect_to article_url(@article), notice: "Article was successfully updated." }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url, notice: "Article was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def show_by_slug
    render 'show'
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def set_article_by_slug
    @article = Article.find_by(slug: params[:slug])
  end

  # Generates a slug from title
  # Uniq constraint checked within model
  def generate_slug(article)
    return article.slug unless article.slug.empty?

    article.title.force_encoding('ascii').gsub(' ', '-').downcase
  end

  def article_params
    params.require(:article).permit(:title, :slug, :content_md, :views, :published, :show_in_feed, :brief, :image, :category)
  end

  def init_markdown
    extensions = { no_intra_emphasis: true, fenced_code_blocks: true, disable_indented_code_blocks: true, strikethrough: true, lax_spacing: true, superscript: true, highlight: true, quote: true, footnotes: true, autolink: true, tables: true}
    red_html = Redcarpet::Render::HTML.new( { filter_html: false } )
    Redcarpet::Markdown.new(red_html, extensions)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article.html.erb
    <div class="grid md:grid-cols-3 gap-x-6 xl:gap-x-12 items-center mb-12">
      <div class="mb-8 md:mb-0">
        <div
          class="col-span-1 relative overflow-hidden bg-no-repeat bg-cover relative overflow-hidden bg-no-repeat bg-cover ripple shadow-lg rounded-lg"
          >
                     <% unless article.image.empty? %>
           <%= image_tag(article.image, alt: '',class: 'border rounded w-max-full h-auto')%>
           <% else %>
           <%= image_tag("web/enduroMonster_large.png", alt: '', class: 'border rounded w-maxx-full h-auto', style: '')%>
           <% end %>
          <a href="<%= post_path(article.slug) %>">
            <div class="absolute top-0 right-0 bottom-0 left-0 w-full h-full overflow-hidden bg-fixed opacity-0 hover:opacity-100 transition duration-300 ease-in-out"
              style="background-color: rgba(251, 251, 251, 0.2)"></div>
          </a>
        </div>
      </div>
      <div class="col-span-2 mb-6 md:mb-0">
              <div class="mb-3 text-gray-600 font-medium text-sm flex items-center justify-center md:justify-start">
          [ <%= article.category.upcase %> ]
        </div>
        <a href="<%= post_path(article.slug) %>" class="text-3xl font-bold mb-3"><%= article.title %></a>
        <p><a href="<%= post_path(article.slug) %>" class="text-gray-500">
          <%= article.brief %>
        </a>
        <p>
        <p class="text-gray-500 mb-6">
          <small>Published <u><%= article.updated_at %></u> by
            <a href="<%= post_path(article.slug) %>" class="text-gray-900">Evaldas</a></small>
        </p>

      </div>
    </div>

app/views/articles/_article_read.html.erb
<h1 class="font-medium leading-tight text-5xl mt-0 mb-2 "><%= article_read.title %></h1>
<h6 class="font-medium leading-tight text-base mt-0 mb-2">by Evaldas on <%= article_read.updated_at %></h6>
<% unless article_read.image.empty? %>
<%= image_tag(article_read.image, alt: '',class: 'border rounded w-max-full h-auto')%>
<% end %>
<p class="text-base font-light leading-relaxed mt-0 mb-4 ">
<%= article_read.content_html.html_safe %>
</p>

app/views/articles/_featured_article.html.erb
<section class="mb-32 text-gray-800 text-center">

  <!-- Single article -->
  <div class="flex flex-wrap justify-center mb-12">
    <div class="grow-0 shrink-0 basis-auto w-full md:w-10/12 px-3">
      <div
        class="relative overflow-hidden bg-no-repeat bg-cover relative overflow-hidden bg-no-repeat bg-cover ripple shadow-lg mb-6 rounded-lg"
        data-mdb-ripple="true" data-mdb-ripple-color="light">
        <img src="https://mdbootstrap.com/img/new/slides/080.jpg" class="w-full" />
        <a href="#!">
          <div class="absolute top-0 right-0 bottom-0 left-0 w-full h-full overflow-hidden bg-fixed opacity-0 hover:opacity-100 transition duration-300 ease-in-out"
            style="background-color: rgba(251, 251, 251, 0.15)"></div>
        </a>
      </div>
    </div>

    <div class="grow-0 shrink-0 basis-auto w-full md:w-8/12 xl:w-6/12 px-3">
      <h5 class="text-lg font-bold mb-3">This is a very long post title</h5>
      <p class="text-gray-500 mb-4">
        <small>Published <u>15.01.2022</u> by
          <a href="" class="text-gray-900">Anna Maria Doe</a></small>
      </p>
      <p class="mb-6">
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Culpa
        atque hic, officiis blanditiis accusantium veritatis ullam?
        Maiores atque autem velit officiis molestiae voluptates suscipit
        eligendi, vero expedita sequi, doloremque modi?
      </p>
      <a data-mdb-ripple="true" data-mdb-ripple-color="light"
        class="inline-block px-6 py-2.5 bg-blue-600 text-white font-medium text-xs leading-tight uppercase rounded-full shadow-md hover:bg-blue-700 hover:shadow-lg focus:bg-blue-700 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-blue-800 active:shadow-lg transition duration-150 ease-in-out"
        href="" role="button">Read more</a>
    </div>
  </div>
  <!-- Single article -->

</section>

app/views/articles/_form.html.erb
<%= form_with(model: article, class: "contents") do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :title %>
    <%= form.text_field :title, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :slug %>
    <%= form.text_field :slug, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>
  <div class="my-5">
    <%= form.label :image %>
    <%= form.text_field :image, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :category %>
    <%= form.select :category, options_for_select(Article.categories.map {|key, value| [key.to_s.titleize, key ]}) %>  
  </div>

  <div class="my-5">
    <%= form.label :brief %>
    <%= form.text_area :brief, rows: 3, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :content_md %>
    <%= form.text_area :content_md, rows: 35, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
  <%= form.label :published, style: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  <%= form.check_box :published %>
  </div>

  <div class="my-5">
  <%= form.label :show_in_feed, style: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  <%= form.check_box :show_in_feed %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/articles/_landing_articles.html.erb
  
  
  
  <section class="mb-32 text-gray-800 text-center md:text-left">
    <h2 class="text-3xl font-bold mb-12 text-center"></h2>
    <%= render @articles.where(published: true, show_in_feed:true).order(:created_at).reverse_order %>
    <div class="flex justify-center">

  <!-- PAGINATION -->
  <!--
  <nav aria-label="Page navigation">
    <ul class="flex list-style-none">
      <li class="page-item disabled"><a
          class="page-link relative block py-1.5 px-3 border-0 bg-transparent outline-none transition-all duration-300 rounded-full text-gray-500 pointer-events-none focus:shadow-none"
          href="#" tabindex="-1" aria-disabled="true">Previous</a></li>
      <li class="page-item"><a
          class="page-link relative block py-1.5 px-3 border-0 bg-transparent outline-none transition-all duration-300 rounded-full text-gray-800 hover:text-gray-800 hover:bg-gray-200 focus:shadow-none"
          href="#">1</a></li>
      <li class="page-item disabled"><a
          class="page-link relative block py-1.5 px-3 border-0 bg-blue-600 outline-none transition-all duration-300 rounded-full text-white hover:text-white hover:bg-blue-600 shadow-md focus:shadow-md"
          href="#">2 <span class="visually-hidden"></span></a></li>
      <li class="page-item"><a
          class="page-link relative block py-1.5 px-3 border-0 bg-transparent outline-none transition-all duration-300 rounded-full text-gray-800 hover:text-gray-800 hover:bg-gray-200 focus:shadow-none"
          href="#">3</a></li>
      <li class="page-item"><a
          class="page-link relative block py-1.5 px-3 border-0 bg-transparent outline-none transition-all duration-300 rounded-full text-gray-800 hover:text-gray-800 hover:bg-gray-200 focus:shadow-none"
          href="#">Next</a></li>
    </ul>
  </nav>
  -->
  <!-- PAGINATION -->
</div>
  </section>

app/views/articles/_navbar.html.erb
<header>
  <!-- Navbar -->
  <nav class="navbar navbar-expand-lg shadow-md py-2 bg-white relative flex items-center w-full justify-between">
    <div class="px-6 w-full flex flex-wrap items-center justify-between">
      <div class="flex items-center">
        <button
          class="navbar-toggler border-0 py-3 lg:hidden leading-none text-xl bg-transparent text-gray-600 hover:text-gray-700 focus:text-gray-700 transition-shadow duration-150 ease-in-out mr-2"
          type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContentY"
          aria-controls="navbarSupportedContentY" aria-expanded="false" aria-label="Toggle navigation">
          <svg aria-hidden="true" focusable="false" data-prefix="fas" class="w-5" role="img"
            xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512">
            <path fill="currentColor"
              d="M16 132h416c8.837 0 16-7.163 16-16V76c0-8.837-7.163-16-16-16H16C7.163 60 0 67.163 0 76v40c0 8.837 7.163 16 16 16zm0 160h416c8.837 0 16-7.163 16-16v-40c0-8.837-7.163-16-16-16H16c-8.837 0-16 7.163-16 16v40c0 8.837 7.163 16 16 16zm0 160h416c8.837 0 16-7.163 16-16v-40c0-8.837-7.163-16-16-16H16c-8.837 0-16 7.163-16 16v40c0 8.837 7.163 16 16 16z">
            </path>
          </svg>
        </button>
      </div>
      <div class="navbar-collapse collapse grow items-center" id="navbarSupportedContentY">
        <ul class="navbar-nav mr-auto lg:flex lg:flex-row">
          <li class="nav-item">
            <a class="nav-link block pr-2 lg:px-2 py-2 text-gray-600 hover:text-gray-700 focus:text-gray-700 transition duration-150 ease-in-out"
              href="#!" data-mdb-ripple="true" data-mdb-ripple-color="light">Home</a>
          </li>
          <li class="nav-item mb-2 lg:mb-0">
            <a class="nav-link block pr-2 lg:px-2 py-2 text-gray-600 hover:text-gray-700 focus:text-gray-700 transition duration-150 ease-in-out"
              href="#!" data-mdb-ripple="true" data-mdb-ripple-color="light">About</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <!-- Navbar -->

  <!-- Background image -->
  <div class="relative overflow-hidden bg-no-repeat bg-cover" style="
    background-position: 50%;
    background-image: url('https://mdbcdn.b-cdn.net/img/new/slides/146.webp');
    height: 350px;
  ">
    <div class="absolute top-0 right-0 bottom-0 left-0 w-full h-full overflow-hidden bg-fixed"
      style="background-color: rgba(0, 0, 0, 0.75)">
      <div class="flex justify-center items-center h-full">
        <div class="text-center text-white px-6 md:px-12">
          <h1 class="text-5xl font-bold mt-0 mb-6">Heading</h1>
          <h3 class="text-3xl font-bold mb-8">Subheading</h3>
        </div>
      </div>
    </div>
  </div>
  <!-- Background image -->
</header>

app/views/articles/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing article</h1>

  <%= render "form", article: @article %>

  <%= link_to "Show this article", @article, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to articles", articles_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/articles/index.html.erb
<%= render 'landing_articles' %>

app/views/articles/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New article</h1>

  <%= render "form", article: @article %>

  <%= link_to 'Back to articles', articles_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/articles/show.html.erb
<div class="mx-auto md:w-2/3 w-full">
    <%= render partial: 'article_read', object: @article %>
</div>
<hr>

<% if user_signed_in?%>
<br>
<div class="flex justify-center px-5 ">
<div class="block p-6 rounded-lg shadow-lg bg-sky-500 max-w-sm px-5 py-5">
<h5 class="text-gray-900 text-xl leading-tight font-medium mb-2">Creator Area</h5>
<%= link_to 'Edit post', edit_article_path(@article), class: "mt-2 rounded-lg py-3 px-5 bg-amber-200 inline-block font-medium" %>
<div class="inline-block ml-2">
<%= button_to 'Delete post', article_path(@article), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-red-300 font-medium" %>
</div>
</div>
</div>
<br>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>My Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>
  <body>
    <%= render 'layouts/components/navbar' %>
        <%= render 'layouts/components/notice' %>
    <% if request.path == root_path %>
    <%= render 'layouts/components/landing' %>
    <% end %>
    <div class="container my-24 px-6 mx-auto">
    <%= yield %>
    </div>
    <%= render 'layouts/components/footer' %>
  </body>
</html>

app/views/layouts/components/_footer.html.erb
<footer class="text-center lg:text-left">
  <div class="text-white text-center p-4" style="background-color: #23262c;">
  <p>©2022: <a href="https://github.com/e-crede" target="_blank" ><u>Evaldas</u></a></p>
  </div>
</footer>

app/views/layouts/components/_landing.html.erb
  <!-- Background image -->
  <div class="relative overflow-hidden bg-no-repeat bg-cover" style="
    background-position: 50%;
    background-image: 'web/enduroMonster_large.png';
    height: 200px;
  ">
    <div class="absolute top-0 right-0 bottom-0 left-0 w-full h-full overflow-hidden bg-fixed"
      style="background-color: #23262c">
      <div class="flex justify-center items-center h-full">
      <%= image_tag("web/enduroMonster_large.png", alt: 'EnduroMonster',class: 'h-16', style: 'height: 100px')%>
        <div class="text-center text-white px-6 md:px-12">
          <h1 class="text-5xl font-bold mt-0 mb-6"></h1>
          <h3 class="text-3xl font-bold mb-8">Experiences - documented.</h3>
        </div>
      </div>
    </div>
  </div>
  <!-- Background image -->

app/views/layouts/components/_navbar.html.erb
<header>
  <!-- Navbar -->
  <nav class="navbar navbar-expand-lg shadow-md py-2 bg-white relative flex items-center w-full justify-between", style="background-color: #23262c;>
    <div class="px-6 w-full flex flex-wrap items-center justify-between">
      <div class="flex items-center">
        <button
          class="navbar-toggler border-0 py-3 lg:hidden leading-none text-xl bg-transparent text-white hover:text-gray-700 focus:text-gray-700 transition-shadow duration-150 ease-in-out mr-2"
          type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContentY"
          aria-controls="navbarSupportedContentY" aria-expanded="false" aria-label="Toggle navigation">
          <svg aria-hidden="true" focusable="false" data-prefix="fas" class="w-5" role="img"
            xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512">
            <path fill="currentColor"
              d="M16 132h416c8.837 0 16-7.163 16-16V76c0-8.837-7.163-16-16-16H16C7.163 60 0 67.163 0 76v40c0 8.837 7.163 16 16 16zm0 160h416c8.837 0 16-7.163 16-16v-40c0-8.837-7.163-16-16-16H16c-8.837 0-16 7.163-16 16v40c0 8.837 7.163 16 16 16zm0 160h416c8.837 0 16-7.163 16-16v-40c0-8.837-7.163-16-16-16H16c-8.837 0-16 7.163-16 16v40c0 8.837 7.163 16 16 16z">
            </path>
          </svg>
        </button>
      </div>
      <div class="navbar-collapse collapse grow items-center" id="navbarSupportedContentY">
        <ul class="navbar-nav mr-auto lg:flex lg:flex-row">
          <li class="nav-item">
            <a class="nav-link block pr-2 lg:px-2 py-2 text-white hover:text-gray-700 focus:text-gray-700 transition duration-150 ease-in-out"
              href="<%= root_path %>" data-mdb-ripple="true" data-mdb-ripple-color="light">Home</a>
          </li> 
          <li class="nav-item mb-2 lg:mb-0">
            <a class="nav-link block pr-2 lg:px-2 py-2 text-white hover:text-gray-700 focus:text-gray-700 transition duration-150 ease-in-out"
              href="<%= post_path('about') %>" data-mdb-ripple="true" data-mdb-ripple-color="light">About</a>
          </li>

          <% if user_signed_in? %>
          <li class="nav-item mb-2 lg:mb-0">
            <a class="nav-link block pr-2 lg:px-2 py-2 text-white hover:text-gray-700 focus:text-gray-700 transition duration-150 ease-in-out"
              href="<%= new_article_path %>" data-mdb-ripple="true" data-mdb-ripple-color="light">New Article</a>
          </li>
          <li class="nav-item mb-2 lg:mb-0">
          <%= button_to "Logout", destroy_user_session_path, method: :delete, class: "nav-link block pr-2 lg:px-2 py-2 text-white hover:text-gray-700 focus:text-gray-700 transition duration-150 ease-in-out"  %>
          </li>
          <% end %>
          <% unless user_signed_in? %>
                    <li class="nav-item mb-2 lg:mb-0">
            <a class="nav-link block pr-2 lg:px-2 py-2 text-white hover:text-gray-700 focus:text-gray-700 transition duration-150 ease-in-out"
              href="<%= new_user_session_path %>" data-mdb-ripple="true" data-mdb-ripple-color="light">Login</a>
          </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
  <!-- Navbar -->
</header>

app/views/layouts/components/_notice.html.erb
  <% if notice.present? %>
  <div class="rounded-lg bg-blue-100 py-5 px-6 mb-4 text-base text-blue-700 mb-3" role="alert" id="notice">
  <%= notice %>
  </div>
  <% end %>